produtos/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "produtos"
urlpatterns = [
    path('', views.index, name="index"),
    path('todos_produtos/', views.todos_produtos, name="todos_produtos"),
    path('produto_detalhado/<int:id_produto>/', views.produto_detalhado, name="produto_detalhado"),
    path('editar_produto/<int:id_produto>/', views.editar_produto, name="editar_produto"),
    path('excluir_produto/<int:id_produto>/', views.excluir_produto, name="excluir_produto"),
    path('incluir_produto/', views.incluir_produto, name="incluir_produto"),
    path('salva_produto_bd/', views.salva_produto_bd, name="salva_produto_bd"),

    
    # Fornecedores 
    path('todos_fornecedores/', views.todos_fornecedores, name="todos_fornecedores"),
]

projetointegrador/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("produtos.urls"))
]

produtos/models.py
from django.db import models

# Create your models here.
class Fornecedor(models.Model):
    razao_social = models.CharField(max_length=80)
    nome_fantasia = models.CharField(max_length=80)
    cnpj = models.CharField(max_length=14)
    telefone = models.CharField(max_length=11)
    email = models.EmailField(max_length=255)
    logradouro = models.CharField(max_length=255)
    numero_logradouro = models.CharField(max_length=5)
    bairro = models.CharField(max_length=255)
    cidade = models.CharField(max_length=255)
    cep = models.CharField(max_length=8)

    def __str__(self) -> str:
        return self.razao_social


class Marca(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.nome


class Produto(models.Model):
    descricao = models.CharField(max_length=255)
    referencia_fornecedor = models.CharField(max_length=255)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE, default="")
    fornecedor = models.ForeignKey(Fornecedor, on_delete=models.CASCADE, default="")
    preco_custo = models.DecimalField(max_digits=10, decimal_places=2)
    preco_venda = models.DecimalField(max_digits=10, decimal_places=2)
    data_compra = models.DateField()
    ultima_modificacao = models.DateField(auto_now=True) # Adiciona a data no momento da execucao do comando save()
    ncm = models.CharField(max_length=8)

    def __str__(self) -> str:
        return self.descricao + " | " + self.referencia_fornecedor


    def formata_data_compra(self):
        return self.data_compra.strftime('%Y-%m-%d')


    def formata_ultima_modificacao(self):
        return self.ultima_modificacao.strftime('%Y-%m-%d')
    

produtos/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from . models import Produto, Fornecedor, Marca

# -->   Aqui ficam todas as funcoes responsaveis por tratar os dados capturados do
#       banco de dados e envia-las para um template html <--

# Essa requisicao trata de apenas renderizar a pagina inicial
def index(requisicao):
    #return HttpResponse("Olaaaa")
    return render(requisicao, "produtos/index.html")


# Essa requisicao apenas obtem forncedores e marcas do bd, renderiza o formulario
# Assim que o formulario e submetido envia para funcao que salva de fato o novo produto no bd
def incluir_produto(requisicao):
    try:
        fornecedores = Fornecedor.objects.all()
        marcas = Marca.objects.all()

        # A redundancia em atual_fornecedor e atual_marca e devida a hora de verificar e igual, so funciona comparando string com string
        contexto = { 
            "fornecedores" : fornecedores, 
            "marcas" : marcas,
        }
    except Produto.DoesNotExist:
        raise Http404("Erro ao tentar detalhar um produto")
    except Marca.DoesNotExist:
        raise Http404("Erro ao tentar detalhar um produto")
    return render(requisicao, "produtos/incluir_produto.html", contexto)


# Essa funcao apenas obtem os dados do formulario e cria de fato um novo produto
# Redirecionando para todos_produtos
def salva_produto_bd(requisicao):
    descricao = requisicao.POST["descricao"]
    referencia_fornecedor = requisicao.POST["referencia_fornecedor"]
    marca = Marca.objects.get(nome=requisicao.POST["marca"])
    fornecedor = Fornecedor.objects.get(razao_social=requisicao.POST["fornecedor"])
    preco_custo = requisicao.POST["preco_custo"]
    preco_venda = requisicao.POST["preco_venda"]
    data_compra = requisicao.POST["data_compra"]
    ncm = requisicao.POST["ncm"]
    novo_produto = Produto.objects.create(descricao=descricao,
                                          referencia_fornecedor=referencia_fornecedor,
                                          marca=marca,
                                          fornecedor=fornecedor,
                                          preco_custo=preco_custo,
                                          preco_venda=preco_venda,
                                          data_compra=data_compra,
                                          ncm=ncm
                                        )
    novo_produto.save()
    return HttpResponseRedirect(reverse("produtos:todos_produtos"))



# Essa requisicao trata de capturar do banco de dados todos os produtos e 
# retornar isso para o template atraves do dicionario 'contexto'
def todos_produtos(requisicao):
    try:
        todos_produtos =  Produto.objects.order_by("-id").all()
        contexto = { "todos_produtos" : todos_produtos }
    except Produto.DoesNotExist:
        raise Http404("Erro ")
    return render(requisicao, "produtos/todos_produtos.html", contexto)


# Essa requisicao trata de capturar do banco de dados o ID igual a chave primaria (id) de produto e 
# se existir um, é retornado tal produto para o template atraves do dicionario 'contexto'
def produto_detalhado(requisicao, id_produto):
    try:
        produto = Produto.objects.get(pk=id_produto)
        fornecedores = Fornecedor.objects.all()
        marcas = Marca.objects.all()

        # A redundancia em atual_fornecedor e atual_marca e devida a hora de verificar e igual, so funciona comparando string com string
        contexto = { 
            "produto" : produto, 
            "fornecedores" : fornecedores, 
            "atual_fornecedor" : str(produto.fornecedor), 
            "marcas" : marcas,
            "atual_marca" : str(produto.marca),
        }

    except Produto.DoesNotExist:
        raise Http404("Erro ao tentar detalhar um produto")
    return render(requisicao, "produtos/produto_detalhado.html", contexto)


# Essa requisicao trata de captura atraves do metodo POST os valores obtidos no formulario
# e atualizar o registro no banco de dados. Apos isso ele redireciona para o a view 'produto_detalhado'
def editar_produto(requisicao, id_produto):
    try:
        produto = Produto.objects.get(pk=id_produto)

        produto.descricao = requisicao.POST["descricao"]
        produto.referencia_fornecedor = requisicao.POST["referencia_fornecedor"]
        produto.marca = Marca.objects.get(nome=requisicao.POST["marca"])
        produto.fornecedor = Fornecedor.objects.get(razao_social=requisicao.POST["fornecedor"])
        produto.preco_custo = requisicao.POST["preco_custo"]
        produto.preco_venda = requisicao.POST["preco_venda"]
        produto.data_compra = requisicao.POST["data_compra"]
        produto.ncm = requisicao.POST["ncm"]

        produto.save()
    except Produto.DoesNotExist:
        raise Http404("Erro ao tentar detalhar um produto")
    return HttpResponseRedirect(reverse("produtos:todos_produtos"))

    
# Essa requisicao exclui o produto e redireciona para o view todos_produtos
def excluir_produto(requisicao, id_produto):
    try:
        Produto.objects.get(pk=id_produto).delete()
    except Produto.DoesNotExist:
        raise Http404("Erro ao tentar excluir o produto")
    return HttpResponseRedirect(reverse("produtos:todos_produtos"))


#################### Fornecedor ################

# Essa requisicao trata de capturar do banco de dados todos os fornecedores e 
# retornar isso para o template atraves do dicionario 'contexto'
def todos_fornecedores(requisicao):
    try:
        todos_fornecedores = Fornecedor.objects.all()
        contexto = { "todos_fornecedores" : todos_fornecedores }
    except Fornecedor.DoesNotExist:
        raise Http404("Erro ao tentar exibir todos os fornecedores!")
    return render(requisicao, "produtos/todos_fornecedores.html", contexto)
    

produtos/templates/produtos/incluir_produto.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <!-- Google Icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
</head>
<body>
    <header class="container">
        <h2>Incluir Produto</h2>
        <a href="{% url 'produtos:index' %}">Voltar para página inicial</a>
        <hr>
    </header>

    <main class="container">
        <!-- Ajustar url do action e terminar de configurar a view -->
        <form action="{% url 'produtos:salva_produto_bd' %}" method="POST">
            {% csrf_token %}
            <fieldset>
                <legend><h3>Preencha o seguinte formulario</h3></legend>
                <div class="mb-3">
                    <label for="id">Id</label>
                    <input type="text" name="id" id="id" value="{{ produto.id }}" disabled>
                </div>

                <div class="mb-3">
                    <label for="descricao">Descrição</label>
                    <input type="text" name="descricao" id="descricao" value="{{ produto.descricao }}">
                </div>

                <div class="mb-3">
                    <label for="referencia_fornecedor">Referencia</label>
                    <input type="text" name="referencia_fornecedor" id="referencia_fornecedor" value="{{ produto.referencia_fornecedor }}">
                </div>

                <div class="w-25 mb-3">
                    <label for="fornecedor">Fornecedor</label>  
                    <select class="form-select" aria-label="Padrao fornecedor" id="fornecedor" name="fornecedor">
                        <option value="{{ produto.fornecedor }}" /selected>{{ produto.fornecedor }}</option>
                        {% for fornecedor in fornecedores %}
                                {% if atual_fornecedor != fornecedor.razao_social %}
                                    <option value="{{ fornecedor.razao_social }}">{{ fornecedor.razao_social }}</option>
                                {% endif %}
                        {% endfor %}
                    </select>
                </div>

                <div class="w-25 mb-3">
                    <label for="marca">Marca</label>
                    <select class="form-select" aria-label="Padrao marca" id="marca" name="marca">
                        <option value="{{ produto.marca }}" /selected>{{ produto.marca }}</option>
                        {% for marca in marcas %}
                            {% if atual_marca != marca.nome %}
                                <option value="{{ marca.nome }}">{{ marca.nome }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                
                <div class="mb-3">
                    <label for="preco_custo">Preco Custo</label>
                    <input type="number" name="preco_custo" id="preco_custo" value="{{ produto.preco_custo }}" step="0.01">
                </div>

                <div class="mb-3">
                    <label for="preco_venda">Preco Venda</label>
                    <input type="number" name="preco_venda" id="preco_venda" value="{{ produto.preco_venda }}" step="0.01">
                </div>

                <div class="mb-3">
                    <label for="ncm">NCM</label>
                    <input type="text" name="ncm" id="ncm" value="{{ produto.ncm }}">
                </div>

                <div class="mb-3">
                    <label for="data_compra">Data Compra</label>
                    <input type="date" name="data_compra" id="data_compra" value="{{ produto.formata_data_compra }}" required>
                </div>

                <div class="mb-3">
                    <label for="ultima_modificacao">Ultima Modificação</label>
                    <!-- Esta disabled porque a data sera modificada automaticamente quando salvar -->
                    <input type="date" name="ultima_modificacao" id="ultima_modificacao" value="{{ produto.formata_ultima_modificacao }}" disabled>
                </div>

                <input type="submit" class="btn btn-primary" value="Inserir">
            </fieldset>
        </form>
    </main>
</body>
</html>

produtos/templates/produtos/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Inicial</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</head>
<body>
    <header class="container">
        <h2>Sistema Projeto Integrador UNIVESP</h2> 
        <hr>
    </header>
    <main class="container">
        <div class="card" style="width: 18rem;">
            <div class="card-header">
              Menu
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><a href="{% url 'produtos:todos_produtos' %}">Visualizar todos os produtos</a></li>
              <li class="list-group-item"><a href="{% url 'produtos:incluir_produto'%}">Incluir produto</a></li>
              <li class="list-group-item"><a href="{% url 'produtos:todos_fornecedores'%}">Visualizar todos os fornecedores</a></li>
            </ul>
          </div>
    </main>
</body>
</html>

produtos/templates/produtos/produto_detalhado.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</head>
<body>
    <header class="container">
        <h2>Produto Detalhado</h2>
        <a href="{% url 'produtos:todos_produtos' %}">Voltar para todos os produtos</a>
        <hr>
    </header>
    <main class="container">
        <form action="{% url 'produtos:editar_produto' produto.id %}" method="POST">
            {% csrf_token %}
            <fieldset>
                <legend><h3>Editar produto</h3></legend>
                <div class="mb-3">
                    <label for="id">Id</label>
                    <input type="text" name="id" id="id" value="{{ produto.id }}" disabled>
                </div>

                <div class="mb-3">
                    <label for="descricao">Descrição</label>
                    <input type="text" name="descricao" id="descricao" value="{{ produto.descricao }}">
                </div>

                <div class="mb-3">
                    <label for="referencia_fornecedor">Referencia</label>
                    <input type="text" name="referencia_fornecedor" id="referencia_fornecedor" value="{{ produto.referencia_fornecedor }}">
                </div>

                <div class="w-25 mb-3">
                    <label for="fornecedor">Fornecedor</label>  
                    <select class="form-select" aria-label="Padrao fornecedor" id="fornecedor" name="fornecedor">
                        <option value="{{ produto.fornecedor }}" /selected>{{ produto.fornecedor }}</option>
                        {% for fornecedor in fornecedores %}
                                {% if atual_fornecedor != fornecedor.razao_social %}
                                    <option value="{{ fornecedor.razao_social }}">{{ fornecedor.razao_social }}</option>
                                {% endif %}
                        {% endfor %}
                    </select>
                </div>

                <div class="w-25 mb-3">
                    <label for="marca">Marca</label>
                    <select class="form-select" aria-label="Padrao marca" id="marca" name="marca">
                        <option value="{{ produto.marca }}" /selected>{{ produto.marca }}</option>
                        {% for marca in marcas %}
                            {% if atual_marca != marca.nome %}
                                <option value="{{ marca.nome }}">{{ marca.nome }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                
                <div class="mb-3">
                    <label for="preco_custo">Preco Custo</label>
                    <input type="number" name="preco_custo" id="preco_custo" value="{{ produto.preco_custo }}" step="0.01">
                </div>

                <div class="mb-3">
                    <label for="preco_venda">Preco Venda</label>
                    <input type="number" name="preco_venda" id="preco_venda" value="{{ produto.preco_venda }}" step="0.01">
                </div>

                <div class="mb-3">
                    <label for="ncm">NCM</label>
                    <input type="text" name="ncm" id="ncm" value="{{ produto.ncm }}">
                </div>

                <div class="mb-3">
                    <label for="data_compra">Data Compra</label>
                    <input type="date" name="data_compra" id="data_compra" value="{{ produto.formata_data_compra }}" required>
                </div>

                <div class="mb-3">
                    <label for="ultima_modificacao">Ultima Modificação</label>
                    <!-- Esta disabled porque a data sera modificada automaticamente quando salvar -->
                    <input type="date" name="ultima_modificacao" id="ultima_modificacao" value="{{ produto.formata_ultima_modificacao }}" disabled>
                </div>

                <input type="submit" class="btn btn-primary" value="Editar">

                <button type="button" class="btn btn-danger">
                    <a class="link-light text-decoration-none" href="{% url 'produtos:excluir_produto' produto.id %}">Excluir</a>
                </button>
            </fieldset>
        </form>
    </main>
</body>
</html>

produtos/templates/produtos/todos_fornecedores.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</head>
<body>
    <h2>Lista de Forncedores</h2>
    <ul>
        {% for fornecedor in todos_fornecedores %}
            <li> {{ fornecedor.razao_social }} | {{ fornecedor.telefone }}</li>
        {% endfor %}
    </ul>
</body>
</html>

produtos/templates/produtos/todos_produtos.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <!-- Google Icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
</head>
<body>
    <header class="container">
        <h2>Lista de Produtos</h2>
        <a href="{% url 'produtos:index' %}">Voltar para página inicial</a>
        <hr>
    </header>

    <main class="container">
        <table class=" table table-hover">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Descrição</th>
                    <th>Referencia</th>
                    <th>Marca</th>
                    <th>Fornecedor</th>
                    <th>Preco custo</th>
                    <th>Preco Venda</th>
                    <th>Ncm</th>
                    <th>Data Compra</th>
                    <th>Última Modificacao</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                {% for produto in todos_produtos %}
                    <tr>
                        <td> {{ produto.id }} </td>
                        <td> {{ produto.descricao }} </td>
                        <td> {{ produto.referencia_fornecedor }} </td>
                        <td> {{ produto.marca }} </td>
                        <td> {{ produto.fornecedor }} </td>
                        <td> {{ produto.preco_custo }} </td>
                        <td> {{ produto.preco_venda }} </td>
                        <td> {{ produto.ncm }} </td>
                        <td> {{ produto.formata_data_compra }} </td>
                        <td> {{ produto.formata_ultima_modificacao }} </td>
                        <!-- Envia o id do produto atual na funcao produto_detalhado  -->
                        <td> <a href="{% url 'produtos:produto_detalhado' produto.id %} ">
                            <span class="material-symbols-outlined">edit</span>
                            </a> 
                            <a href="{% url 'produtos:excluir_produto' produto.id %}">
                                <span class="material-symbols-outlined">delete</span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
</body>
</html>